// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/account_settings/account_settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:hw_hub_mobile/features/account_settings/data/account_settings_repository.dart'
    as _i4;
import 'package:hw_hub_mobile/features/account_settings/data/models/notification_settings_dto.dart'
    as _i3;
import 'package:hw_hub_mobile/features/account_settings/data/models/user_profile_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileDto_0 extends _i1.SmartFake
    implements _i2.UserProfileDto {
  _FakeUserProfileDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettingsDto_1 extends _i1.SmartFake
    implements _i3.NotificationSettingsDto {
  _FakeNotificationSettingsDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountSettingsRepository extends _i1.Mock
    implements _i4.AccountSettingsRepository {
  MockAccountSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfileDto> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i5.Future<_i2.UserProfileDto>.value(
              _FakeUserProfileDto_0(this, Invocation.method(#fetchProfile, [])),
            ),
          )
          as _i5.Future<_i2.UserProfileDto>);

  @override
  _i5.Future<_i2.UserProfileDto> updateProfile({
    required String? displayName,
    required String? locale,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #locale: locale,
            }),
            returnValue: _i5.Future<_i2.UserProfileDto>.value(
              _FakeUserProfileDto_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #displayName: displayName,
                  #locale: locale,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserProfileDto>);

  @override
  _i5.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> createIconUploadUrl({
    required String? fileName,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createIconUploadUrl, [], {
              #fileName: fileName,
              #mimeType: mimeType,
            }),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> uploadToS3({
    required String? uploadUrl,
    required _i6.Uint8List? bytes,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadToS3, [], {
              #uploadUrl: uploadUrl,
              #bytes: bytes,
              #mimeType: mimeType,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateIcon({required String? fileKey}) =>
      (super.noSuchMethod(
            Invocation.method(#updateIcon, [], {#fileKey: fileKey}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.NotificationSettingsDto> fetchNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNotificationSettings, []),
            returnValue: _i5.Future<_i3.NotificationSettingsDto>.value(
              _FakeNotificationSettingsDto_1(
                this,
                Invocation.method(#fetchNotificationSettings, []),
              ),
            ),
          )
          as _i5.Future<_i3.NotificationSettingsDto>);

  @override
  _i5.Future<_i3.NotificationSettingsDto> updateNotificationSettings(
    _i3.NotificationSettingsDto? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationSettings, [settings]),
            returnValue: _i5.Future<_i3.NotificationSettingsDto>.value(
              _FakeNotificationSettingsDto_1(
                this,
                Invocation.method(#updateNotificationSettings, [settings]),
              ),
            ),
          )
          as _i5.Future<_i3.NotificationSettingsDto>);

  @override
  _i5.Future<void> linkGoogleAccount({required String? idToken}) =>
      (super.noSuchMethod(
            Invocation.method(#linkGoogleAccount, [], {#idToken: idToken}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateThemeMode({required String? themeMode}) =>
      (super.noSuchMethod(
            Invocation.method(#updateThemeMode, [], {#themeMode: themeMode}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
