// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/tasks/tasks_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hw_hub_mobile/features/tasks/data/my_tasks_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MyTasksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyTasksRepository extends _i1.Mock implements _i2.MyTasksRepository {
  MockMyTasksRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.HouseworkTaskDto>> fetchOpenTasks({
    required int? householdId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOpenTasks, [], {#householdId: householdId}),
            returnValue: _i3.Future<List<_i2.HouseworkTaskDto>>.value(
              <_i2.HouseworkTaskDto>[],
            ),
          )
          as _i3.Future<List<_i2.HouseworkTaskDto>>);

  @override
  _i3.Future<void> updateTaskStatus({
    required int? taskId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [], {
              #taskId: taskId,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> bulkUpdateStatus({
    required List<int>? taskIds,
    required String? status,
    String? skippedReason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateStatus, [], {
              #taskIds: taskIds,
              #status: status,
              #skippedReason: skippedReason,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
