// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/notifications/notifications_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hw_hub_mobile/features/notifications/data/models/notification_dto.dart'
    as _i4;
import 'package:hw_hub_mobile/features/notifications/data/notification_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NotificationDto>> fetchNotifications({
    required int? limit,
    required bool? markRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNotifications, [], {
              #limit: limit,
              #markRead: markRead,
            }),
            returnValue: _i3.Future<List<_i4.NotificationDto>>.value(
              <_i4.NotificationDto>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationDto>>);

  @override
  _i3.Future<int> fetchUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#fetchUnreadCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
