// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/housework_assign/housework_assign_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hw_hub_mobile/features/home/data/models/household_member_dto.dart'
    as _i5;
import 'package:hw_hub_mobile/features/housework_assign/data/housework_assign_repository.dart'
    as _i2;
import 'package:hw_hub_mobile/features/tasks/data/models/housework_task_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HouseworkAssignRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHouseworkAssignRepository extends _i1.Mock
    implements _i2.HouseworkAssignRepository {
  MockHouseworkAssignRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.HouseworkTaskDto>> fetchTasks({
    required int? householdId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTasks, [], {#householdId: householdId}),
            returnValue: _i3.Future<List<_i4.HouseworkTaskDto>>.value(
              <_i4.HouseworkTaskDto>[],
            ),
          )
          as _i3.Future<List<_i4.HouseworkTaskDto>>);

  @override
  _i3.Future<List<_i5.HouseholdMemberDto>> fetchMembers({
    required int? householdId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMembers, [], {#householdId: householdId}),
            returnValue: _i3.Future<List<_i5.HouseholdMemberDto>>.value(
              <_i5.HouseholdMemberDto>[],
            ),
          )
          as _i3.Future<List<_i5.HouseholdMemberDto>>);

  @override
  _i3.Future<void> updateAssignee({
    required int? taskId,
    required int? assigneeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAssignee, [], {
              #taskId: taskId,
              #assigneeUserId: assigneeUserId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> bulkSkipPastUnassigned({required List<int>? taskIds}) =>
      (super.noSuchMethod(
            Invocation.method(#bulkSkipPastUnassigned, [], {#taskIds: taskIds}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
