// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/auth/auth_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:hw_hub_mobile/core/models/auth_user.dart' as _i2;
import 'package:hw_hub_mobile/features/auth/data/auth_api.dart' as _i8;
import 'package:hw_hub_mobile/features/auth/data/auth_repository.dart' as _i6;
import 'package:hw_hub_mobile/features/auth/data/models/invitation_info.dart'
    as _i5;
import 'package:hw_hub_mobile/features/auth/data/models/login_response.dart'
    as _i3;
import 'package:hw_hub_mobile/features/auth/data/models/register_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUser_0 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponse_2 extends _i1.SmartFake
    implements _i4.RegisterResponse {
  _FakeRegisterResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvitationInfo_3 extends _i1.SmartFake
    implements _i5.InvitationInfo {
  _FakeInvitationInfo_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthUser> getMyProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, []),
            returnValue: _i7.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(this, Invocation.method(#getMyProfile, [])),
            ),
          )
          as _i7.Future<_i2.AuthUser>);

  @override
  _i7.Future<_i3.LoginResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i7.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LoginResponse>);

  @override
  _i7.Future<_i3.LoginResponse> googleLoginMobile({required String? idToken}) =>
      (super.noSuchMethod(
            Invocation.method(#googleLoginMobile, [], {#idToken: idToken}),
            returnValue: _i7.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#googleLoginMobile, [], {#idToken: idToken}),
              ),
            ),
          )
          as _i7.Future<_i3.LoginResponse>);

  @override
  _i7.Future<_i4.RegisterResponse> register({
    required String? email,
    required String? password,
    required String? displayName,
    required String? locale,
    String? invitationToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
              #locale: locale,
              #invitationToken: invitationToken,
            }),
            returnValue: _i7.Future<_i4.RegisterResponse>.value(
              _FakeRegisterResponse_2(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                  #locale: locale,
                  #invitationToken: invitationToken,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.RegisterResponse>);

  @override
  _i7.Future<void> resendVerification({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerification, [], {#email: email}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyEmail({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> requestPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> confirmPasswordReset({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.InvitationInfo> getInvitation({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#getInvitation, [], {#token: token}),
            returnValue: _i7.Future<_i5.InvitationInfo>.value(
              _FakeInvitationInfo_3(
                this,
                Invocation.method(#getInvitation, [], {#token: token}),
              ),
            ),
          )
          as _i7.Future<_i5.InvitationInfo>);

  @override
  _i7.Future<void> acceptInvitation({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [], {#token: token}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> declineInvitation({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#declineInvitation, [], {#token: token}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i8.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthUser> getMyProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, []),
            returnValue: _i7.Future<_i2.AuthUser>.value(
              _FakeAuthUser_0(this, Invocation.method(#getMyProfile, [])),
            ),
          )
          as _i7.Future<_i2.AuthUser>);

  @override
  _i7.Future<_i3.LoginResponse> login(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#login, [body]),
            returnValue: _i7.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [body])),
            ),
          )
          as _i7.Future<_i3.LoginResponse>);

  @override
  _i7.Future<_i3.LoginResponse> googleLoginMobile(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#googleLoginMobile, [body]),
            returnValue: _i7.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#googleLoginMobile, [body]),
              ),
            ),
          )
          as _i7.Future<_i3.LoginResponse>);

  @override
  _i7.Future<_i4.RegisterResponse> register(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#register, [body]),
            returnValue: _i7.Future<_i4.RegisterResponse>.value(
              _FakeRegisterResponse_2(
                this,
                Invocation.method(#register, [body]),
              ),
            ),
          )
          as _i7.Future<_i4.RegisterResponse>);

  @override
  _i7.Future<void> resendVerification(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerification, [body]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyEmail(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [body]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> requestPasswordReset(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [body]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> confirmPasswordReset(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [body]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.InvitationInfo> getInvitation(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getInvitation, [token]),
            returnValue: _i7.Future<_i5.InvitationInfo>.value(
              _FakeInvitationInfo_3(
                this,
                Invocation.method(#getInvitation, [token]),
              ),
            ),
          )
          as _i7.Future<_i5.InvitationInfo>);

  @override
  _i7.Future<void> acceptInvitation(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvitation, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> declineInvitation(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#declineInvitation, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
