// Mocks generated by Mockito 5.4.6 from annotations
// in hw_hub_mobile/test/features/inquiry/inquiry_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hw_hub_mobile/features/inquiry/data/inquiry_repository.dart'
    as _i3;
import 'package:hw_hub_mobile/features/inquiry/data/models/inquiry_detail_dto.dart'
    as _i2;
import 'package:hw_hub_mobile/features/inquiry/data/models/inquiry_summary_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInquiryDetailDto_0 extends _i1.SmartFake
    implements _i2.InquiryDetailDto {
  _FakeInquiryDetailDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InquiryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInquiryRepository extends _i1.Mock implements _i3.InquiryRepository {
  MockInquiryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.InquirySummaryDto>> fetchInquiries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchInquiries, []),
            returnValue: _i4.Future<List<_i5.InquirySummaryDto>>.value(
              <_i5.InquirySummaryDto>[],
            ),
          )
          as _i4.Future<List<_i5.InquirySummaryDto>>);

  @override
  _i4.Future<int> createInquiry({
    required String? category,
    required String? title,
    required String? body,
    required String? uiClient,
    required String? uiVersion,
    required String? apiVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createInquiry, [], {
              #category: category,
              #title: title,
              #body: body,
              #uiClient: uiClient,
              #uiVersion: uiVersion,
              #apiVersion: apiVersion,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.InquiryDetailDto> fetchInquiry(int? inquiryId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInquiry, [inquiryId]),
            returnValue: _i4.Future<_i2.InquiryDetailDto>.value(
              _FakeInquiryDetailDto_0(
                this,
                Invocation.method(#fetchInquiry, [inquiryId]),
              ),
            ),
          )
          as _i4.Future<_i2.InquiryDetailDto>);

  @override
  _i4.Future<void> addMessage(int? inquiryId, String? body) =>
      (super.noSuchMethod(
            Invocation.method(#addMessage, [inquiryId, body]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> closeInquiry(int? inquiryId) =>
      (super.noSuchMethod(
            Invocation.method(#closeInquiry, [inquiryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> escalateToStaff(int? inquiryId) =>
      (super.noSuchMethod(
            Invocation.method(#escalateToStaff, [inquiryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
